RUB_DELIVERY_RATE = 0
RUB_AIRPORT_RATE = 0
RUB_ATM_RATE = 0
RUB_OFFICE_RATE = 0
RUB_TRANSFER_RATE = 0
RUB_SERVICE_RATE = 0

USDT_DELIVERY_RATE = 0
USDT_AIRPORT_RATE = 0
USDT_ATM_RATE = 0
USDT_OFFICE_RATE = 0
USDT_TRANSFER_RATE = 0
USDT_SERVICE_RATE = 0

USD_DELIVERY_RATE = 0
USD_AIRPORT_RATE = 0
USD_ATM_RATE = 0
USD_OFFICE_RATE = 0
USD_TRANSFER_RATE = 0
USD_SERVICE_RATE = 0